import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nick Johnson | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          crossOrigin="crossOrigin"
          rel="preconnect"
          href="https://fonts.gstatic.com"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <section className={styles.stack1}>
          <h1 className={styles.headline}>
            <strong>Nick Johnson</strong> | Front-End Developer
          </h1>
          <section className={styles.stack2}>
            <h2 className={styles.subheader}>Projects</h2>
            <ul className={styles.list}>
              <li className={styles.listItem}>
                <a href="https://ariaapp.netlify.app" target="_blank">
                  Aria Sequencer
                </a>
              </li>
            </ul>
          </section>
        </section>
      </main>
    </div>
  );
};

export default Home;
